radar/app/bookings/routes.py
#!/usr/bin/env python3
"""
"""

from flask import Blueprint, flash, jsonify, request, render_template, redirect, url_for
from flask_login import login_required, current_user
from app.models import Booking, Flight
from app import db
from flasgger import swag_from


bookings = Blueprint("bookings", __name__)


@bookings.route("/search-flights", methods=["POST"], strict_slashes=False)
def search_flights():
    source = request.form.get("source")
    destination = request.form.get("destination")
    departure_date = request.form.get("departure_date")

    query = Flight.query

    if source:
        query = query.filter_by(source=source)
    if destination:
        query = query.filter_by(destination=destination)
    if departure_date:
        query = query.filter_by(departure_date=departure_date)

    flights = query.all()
    flights_data = [
        {
            "id": flight.id,
            "source": flight.source,
            "destination": flight.destination,
            "departure_date": flight.departure_date,
        }
        for flight in flights
    ]

    # return render_template("search_results.html", flights=flights_data)
    return jsonify({"flights": flights_data})


@bookings.route("/flight-details", methods=["POST"], strict_slashes=False)
@login_required
def flight_details():
    flight_id = request.form.get("flight_id")
    flight = Flight.query.get_or_404(flight_id)
    flight_data = {
        "airline": flight.airline,
        "source": flight.source,
        "destination": flight.destination,
        "departure_date": flight.departure_date,
        "departure_time": flight.departure_time.strftime("%Y-%m-%d %H:%M:%S"),
        "arrival_time": flight.arrival_time.strftime("%Y-%m-%d %H:%M:%S"),
        "available_seats": flight.available_seats,
    }

    return jsonify(flight_data)
    # return render_template("/flight_details", flight_id=flight_id)


@bookings.route("/book-flight", methods=["POST"], strict_slashes=False)
@login_required
@swag_from("../docs/bookings/book-flight.yaml")
def book_flight():
    user_id = current_user.id
    flight_id = request.form.get("flight_id")

    new_booking = Booking(user_id=user_id, flight_id=flight_id)
    db.session.add(new_booking)
    db.session.commit()

    # flash("Flight booked successfully", "success")
    # return redirect(url_for("users.dashboard")), 201
    return (
        jsonify(
            {
                "message": f"Flight booked successfully\n. Your booking id is {new_booking.id}"
            }
        ),
        201,
    )


@bookings.route(
    "/cancel-booking/<int:booking_id>", methods=["POST"], strict_slashes=False
)
@login_required
def cancel_booking(booking_id):
    booking = Booking.query.get(booking_id)

    if booking.user_id == current_user.id:
        if booking.status == "canceled":
            return jsonify({"message": "Booking already cancelled!"}), 301

        booking.status = "canceled"
        db.session.commit()
        return jsonify({"message": "Booking canceled successfully!"}), 201
    else:
        return (
            jsonify({"message": "You don't have permission to cancel this booking."}),
            403,
        )

    # return redirect(url_for("users.dashboard")), 200

radar/app/templates/dashboard.html
<!-- User dashboard -->
<h2>User Dashboard</h2>
<h3>Welcome to the Home Page, {% user %}</h3>

<h3>Upcoming Flights</h3>
{% if upcoming_flights %}
    <ul>
        {% for flight in upcoming_flights %}
            <li>
                {{ flight.flight.source }} to {{ flight.flight.destination }} on {{ flight.flight.departure_date.strftime('%Y-%m-%d %H:%M:%S') }}
                <a href="{{ url_for('bookings.cancel_booking', flight_id=flight.id) }}">Cancel Booking</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No upcoming flights.</p>
{% endif %}

<h3>Booking History</h3>
{% if booking_history %}
    <ul>
        {% for booking in booking_history %}
            <li>
                {{ booking.flight.source }} to {{ booking.flight.destination }} on {{ booking.flight.departure_date.strftime('%Y-%m-%d %H:%M:%S') }}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No booking history.</p>
{% endif %}

radar/app/templates/flight_details.html
<!-- Book Flight-->
<h2>{{ flight.airline }} Flight Details</h2>
<p>Departure Time: {{ flight.departure_time }}</p>
<p>Arrival Time: {{ flight.arrival_time }}</p>
<p>Available Seats: {{ flight.available_seats }}</p>

<a href="{{ url_for('bookings.book_flight', flight_id=flight.id) }}">Book flight</a>

radar/app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Radar</title>
</head>

<body>

    <header>
        <h1>Welcome to Radar</h1>
    </header>

    <main>
        <section id="search-section">
            <h2>Search for Flights</h2>

            <form method="post" action="{{ url_for('bookings.search_flights') }}">
                <label for="source">Source:</label>
                <input type="text" name="source" required>

                <label for="destination">Destination:</label>
                <input type="text" name="destination" required>

                <label for="departure_date">Departure Date:</label>
                <input type="date" name="departure_date">

                <button type="submit">Search Flights</button>
            </form>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 Radar Flight Booking</p>
    </footer>

</body>

</html>

radar/app/templates/search_results.html
<!-- Example: search_results.html -->
<h2>Search Results</h2>
{% if flights %}
    <ul>
        {% for flight in flights %}
            <li>
                {{ flight.source }} to {{ flight.destination }} on {{ flight.departure_date.strftime('%Y-%m-%d %H:%M:%S') }}
                <a href="{{ url_for('bookings.flight_details', flight_id=flight.id) }}">View Details</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No flights found. Please try a different search.</p>
{% endif %}